
name: ğŸš¦Reusable Validate (Format, Lint, Test)

on:
  workflow_call:
      inputs:
        env:
          required: true
          type: string
          description: "Environment to setup for"
          default: dev
        language:
          required: true
          type: string
          description: "Programming language to validate"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  validate:
    name: ${{ inputs.env }} environment
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ğŸ” Load ENV variables
        uses: ./.github/actions/load-tfvars-into-env
        with:
          env-file: './deployments/${{ inputs.env }}/terraform.tfvars'

      - name: ğŸ“¦ Setup Workflow
        uses: ./.github/actions/setup
        with:
          wif_provider: ${{ env.PROVIDER }}
          wif_sa: ${{ env.TF_SA_EMAIL }}

      - name: ğŸš¦ Validate Code
        uses: ./.github/actions/${{ inputs.language }}-validate.yaml
